kind: Service
apiVersion: v1
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: NodePort
  ports:
  - port: 21
    nodePort: 21
    protocol: TCP
    name: ftps
  - port: 21000
    nodePort: 21000
    protocol: TCP
    name: ftps-data
  selector:
    app: ftps
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: services/ftps
        imagePullPolicy: Never
        securityContext:
          privileged: true