kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
    - port:	3000
      nodePort: 3000 
      protocol: TCP
      name: http   
  selector:
    app: grafana
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: services/grafana
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - name: grafana
          containerPort: 3000