kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
    - port: 5100
      nodePort: 5100
      protocol: TCP
      name: http
  selector:
    app: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: mysql
        image: services/mysql
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - name: mysql
          containerPort: 5100
        volumeMounts:
        - name: mysql-storage
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"